//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@interface TPShineLabel : UILabel
{
    _Bool _isAnimating;
}

@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
- (struct CGSize)_maskSize;
- (id)_maskLayer;
- (struct CGPoint)_maskEndingPosition;
- (struct CGPoint)_maskStartingPosition;
- (id)_maskAnimation;
- (id)initWithFrame:(struct CGRect)arg1;

@end

